// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class Acceptance
    {
        [Key]
        [Column("acceptanceId")]
        [StringLength(16)]
        [Unicode(false)]
        public string AcceptanceId { get; set; }
        [Column("status")]
        public bool? Status { get; set; }
        [Column("rating")]
        public int? Rating { get; set; }
        [Column("feedback")]
        public string Feedback { get; set; }
        [Column("constructionContractId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ConstructionContractId { get; set; }
        [Column("imageFile")]
        public string ImageFile { get; set; }

        [ForeignKey("ConstructionContractId")]
        [InverseProperty("Acceptance")]
        public virtual ConstructionContract ConstructionContract { get; set; }
    }
}