// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class Image
    {
        [Key]
        [Column("imageId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ImageId { get; set; }
        [Required]
        [Column("image_data")]
        public string ImageData { get; set; }
        [Column("productId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ProductId { get; set; }
        [Column("processId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ProcessId { get; set; }
        [Column("bracketId")]
        [StringLength(16)]
        [Unicode(false)]
        public string BracketId { get; set; }
        [Column("warrantyReportId")]
        [StringLength(16)]
        [Unicode(false)]
        public string WarrantyReportId { get; set; }

        [ForeignKey("BracketId")]
        [InverseProperty("Image")]
        public virtual Bracket Bracket { get; set; }
        [ForeignKey("ProcessId")]
        [InverseProperty("Image")]
        public virtual Process Process { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("Image")]
        public virtual Product Product { get; set; }
        [ForeignKey("WarrantyReportId")]
        [InverseProperty("Image")]
        public virtual WarrantyReport WarrantyReport { get; set; }
    }
}