// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class PackageProduct
    {
        [Key]
        [Column("productId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ProductId { get; set; }
        [Key]
        [Column("packageId")]
        [StringLength(16)]
        [Unicode(false)]
        public string PackageId { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("quantity")]
        public int? Quantity { get; set; }

        [ForeignKey("PackageId")]
        [InverseProperty("PackageProduct")]
        public virtual Package Package { get; set; }
        [ForeignKey("ProductId")]
        [InverseProperty("PackageProduct")]
        public virtual Product Product { get; set; }
    }
}