// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class PaymentProcess
    {
        [Key]
        [Column("paymentId")]
        [StringLength(16)]
        [Unicode(false)]
        public string PaymentId { get; set; }
        [Column("amount", TypeName = "decimal(18, 0)")]
        public decimal Amount { get; set; }
        [Column("constructionContractId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ConstructionContractId { get; set; }
        [Required]
        [Column("status")]
        [StringLength(50)]
        public string Status { get; set; }
        [Column("taxVNPay")]
        public string TaxVnpay { get; set; }
        [Column("payDateVNPay")]
        public string PayDateVnpay { get; set; }
        [Column("payDate", TypeName = "datetime")]
        public DateTime? PayDate { get; set; }
        [Column("createAt", TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        [Column("isDeposit")]
        public bool IsDeposit { get; set; }
        [Required]
        [Column("accountId")]
        [StringLength(16)]
        [Unicode(false)]
        public string AccountId { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("PaymentProcess")]
        public virtual Account Account { get; set; }
        [ForeignKey("ConstructionContractId")]
        [InverseProperty("PaymentProcess")]
        public virtual ConstructionContract ConstructionContract { get; set; }
    }
}