// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class Team
    {
        [Key]
        [Column("staffLeadId")]
        [StringLength(16)]
        [Unicode(false)]
        public string StaffLeadId { get; set; }
        [Key]
        [Column("staffId")]
        [StringLength(16)]
        [Unicode(false)]
        public string StaffId { get; set; }
        [Column("createAt", TypeName = "datetime")]
        public DateTime CreateAt { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey("StaffId")]
        [InverseProperty("TeamStaff")]
        public virtual Account Staff { get; set; }
        [ForeignKey("StaffLeadId")]
        [InverseProperty("TeamStaffLead")]
        public virtual Account StaffLead { get; set; }
    }
}