// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolarMP.Models
{
    public partial class WarrantyReport
    {
        public WarrantyReport()
        {
            Image = new HashSet<Image>();
            ProductWarrantyReport = new HashSet<ProductWarrantyReport>();
        }

        [Key]
        [Column("warrantyId")]
        [StringLength(16)]
        [Unicode(false)]
        public string WarrantyId { get; set; }
        [Column("manufacturer")]
        public string Manufacturer { get; set; }
        [Column("feature")]
        public string Feature { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("contractId")]
        [StringLength(16)]
        [Unicode(false)]
        public string ContractId { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Column("accountId")]
        [StringLength(16)]
        [Unicode(false)]
        public string AccountId { get; set; }
        [Column("dateTime", TypeName = "datetime")]
        public DateTime? DateTime { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("WarrantyReport")]
        public virtual Account Account { get; set; }
        [ForeignKey("ContractId")]
        [InverseProperty("WarrantyReport")]
        public virtual ConstructionContract Contract { get; set; }
        [InverseProperty("WarrantyReport")]
        public virtual ICollection<Image> Image { get; set; }
        [InverseProperty("Warranty")]
        public virtual ICollection<ProductWarrantyReport> ProductWarrantyReport { get; set; }
    }
}